# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: 'true'
  name: computeinstance-sample-cloudmachine
  labels:
    created-from: image
    network-type: subnetwork
    owner: google
  namespace: activeassist-kcc
spec:
  machineType: n1-standard-1
  zone: us-west1-a
  bootDisk:
    initializeParams:
      size: 24
      type: pd-ssd
      sourceImageRef:
        external: debian-cloud/debian-9
  networkInterface:
  - subnetworkRef:
      name: computeinstance-dep-cloudmachine
    aliasIpRange:
    - ipCidrRange: /24
      subnetworkRangeName: cloudrange
  attachedDisk:
  - sourceDiskRef:
      name: computeinstance-dep1-cloudmachine
    mode: READ_ONLY
    deviceName: proxycontroldisk
    diskEncryptionKeyRaw:
      valueFrom:
        secretKeyRef:
          name: computeinstance-dep-cloudmachine
          key: diskEncryptionKey
  - sourceDiskRef:
      name: computeinstance-dep2-cloudmachine
    mode: READ_WRITE
    deviceName: persistentdisk
  minCpuPlatform: Intel Skylake
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: computeinstance-dep1-cloudmachine
spec:
  description: 'a sample encrypted, blank disk'
  physicalBlockSizeBytes: 4096
  size: 1
  type: pd-ssd
  location: us-west1-a
  diskEncryptionKey:
    rawKey:
      valueFrom:
        secretKeyRef:
          name: computeinstance-dep-cloudmachine
          key: diskEncryptionKey
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: computeinstance-dep2-cloudmachine
spec:
  size: 1
  type: pd-ssd
  location: us-west1-a
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: computeinstance-dep-cloudmachine
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: computeinstance-dep-cloudmachine
spec:
  networkRef:
    name: computeinstance-dep-cloudmachine
  ipCidrRange: 10.2.0.0/16
  region: us-west1
  secondaryIpRange:
  - rangeName: cloudrange
    ipCidrRange: 10.3.16.0/20
---
apiVersion: v1
kind: Secret
metadata:
  name: computeinstance-dep-cloudmachine
stringData:
  diskEncryptionKey: SGVsbG8gZnJvbSBHb29nbGUgQ2xvdWQgUGxhdGZvcm0=
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  labels:
    label-one: value-one
  name: pubsubtopic-sample-kcc
